//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSG", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceProject")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial struct MSG : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string app_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string app_tockenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string app_versionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string op_infosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string op_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool op_statutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_tokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string app_name {
            get {
                return this.app_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.app_nameField, value) != true)) {
                    this.app_nameField = value;
                    this.RaisePropertyChanged("app_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string app_tocken {
            get {
                return this.app_tockenField;
            }
            set {
                if ((object.ReferenceEquals(this.app_tockenField, value) != true)) {
                    this.app_tockenField = value;
                    this.RaisePropertyChanged("app_tocken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string app_version {
            get {
                return this.app_versionField;
            }
            set {
                if ((object.ReferenceEquals(this.app_versionField, value) != true)) {
                    this.app_versionField = value;
                    this.RaisePropertyChanged("app_version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string op_infos {
            get {
                return this.op_infosField;
            }
            set {
                if ((object.ReferenceEquals(this.op_infosField, value) != true)) {
                    this.op_infosField = value;
                    this.RaisePropertyChanged("op_infos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string op_name {
            get {
                return this.op_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.op_nameField, value) != true)) {
                    this.op_nameField = value;
                    this.RaisePropertyChanged("op_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool op_statut {
            get {
                return this.op_statutField;
            }
            set {
                if ((this.op_statutField.Equals(value) != true)) {
                    this.op_statutField = value;
                    this.RaisePropertyChanged("op_statut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_login {
            get {
                return this.user_loginField;
            }
            set {
                if ((object.ReferenceEquals(this.user_loginField, value) != true)) {
                    this.user_loginField = value;
                    this.RaisePropertyChanged("user_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_password {
            get {
                return this.user_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.user_passwordField, value) != true)) {
                    this.user_passwordField = value;
                    this.RaisePropertyChanged("user_password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_token {
            get {
                return this.user_tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.user_tokenField, value) != true)) {
                    this.user_tokenField = value;
                    this.RaisePropertyChanged("user_token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessage", ReplyAction="http://tempuri.org/IHelloService/GetMessageResponse")]
        string GetMessage(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetMessage", ReplyAction="http://tempuri.org/IHelloService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/dispatching", ReplyAction="http://tempuri.org/IHelloService/dispatchingResponse")]
        HelloWebClient.ServiceReference1.MSG dispatching(HelloWebClient.ServiceReference1.MSG msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/dispatching", ReplyAction="http://tempuri.org/IHelloService/dispatchingResponse")]
        System.Threading.Tasks.Task<HelloWebClient.ServiceReference1.MSG> dispatchingAsync(HelloWebClient.ServiceReference1.MSG msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : HelloWebClient.ServiceReference1.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<HelloWebClient.ServiceReference1.IHelloService>, HelloWebClient.ServiceReference1.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string name) {
            return base.Channel.GetMessage(name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync(string name) {
            return base.Channel.GetMessageAsync(name);
        }
        
        public HelloWebClient.ServiceReference1.MSG dispatching(HelloWebClient.ServiceReference1.MSG msg) {
            return base.Channel.dispatching(msg);
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.ServiceReference1.MSG> dispatchingAsync(HelloWebClient.ServiceReference1.MSG msg) {
            return base.Channel.dispatchingAsync(msg);
        }
    }
}
